// Client-side PDF export via a styled print window (MOE Strategist PDF-export pattern, gold theme).
// No backend or external dependencies required — uses the browser's print-to-PDF.

function escapeHtml(str) {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/**
 * Open a print-ready, gold-themed report and trigger the browser's PDF dialog.
 * @param {Object} report
 * @param {string} report.title
 * @param {string} [report.subtitle]
 * @param {Array<{label:string,value:string}>} [report.kpis]
 * @param {Array<{heading:string, rows:Array<[string,string]>}>} [report.sections]
 * @param {string} [report.footer]
 */
export function exportReportPdf(report) {
  const {
    title = 'Eco Connect Report',
    subtitle = 'Ministry of Climate Change & Environment',
    kpis = [],
    sections = [],
    footer = 'Generated by Eco Connect · Falcon Farm Intelligence',
  } = report || {};

  const date = new Date().toLocaleString('en-AE', { dateStyle: 'long', timeStyle: 'short' });

  const kpiHtml = kpis.length
    ? `<div class="kpis">${kpis
        .map(
          (k) => `<div class="kpi"><div class="kpi-val">${escapeHtml(k.value)}</div><div class="kpi-label">${escapeHtml(k.label)}</div></div>`
        )
        .join('')}</div>`
    : '';

  const sectionsHtml = sections
    .map(
      (s) => `
        <section>
          <h2>${escapeHtml(s.heading)}</h2>
          <table>
            ${(s.rows || [])
              .map(([k, v]) => `<tr><td class="k">${escapeHtml(k)}</td><td class="v">${escapeHtml(v)}</td></tr>`)
              .join('')}
          </table>
        </section>`
    )
    .join('');

  const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', Tahoma, sans-serif; color: #2b2113; margin: 0; padding: 40px; background: #fff; }
  .head { border-bottom: 3px solid #9b7a36; padding-bottom: 16px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-end; }
  .brand { font-size: 11px; letter-spacing: 2px; text-transform: uppercase; color: #9b7a36; font-weight: 700; }
  h1 { font-size: 26px; margin: 6px 0 2px; color: #1a1208; }
  .subtitle { font-size: 12px; color: #7a6440; }
  .date { font-size: 11px; color: #9b7a36; text-align: right; }
  .seal { width: 54px; height: 54px; border-radius: 50%; background: linear-gradient(135deg,#9b7a36,#c2a14e); display:flex; align-items:center; justify-content:center; font-size:26px; }
  .kpis { display: flex; gap: 12px; margin: 0 0 24px; flex-wrap: wrap; }
  .kpi { flex: 1; min-width: 120px; border: 1px solid #e6dcc4; border-radius: 12px; padding: 14px; background: #faf6ec; }
  .kpi-val { font-size: 22px; font-weight: 800; color: #9b7a36; }
  .kpi-label { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #7a6440; margin-top: 4px; }
  section { margin-bottom: 22px; }
  h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 1px; color: #1a1208; border-left: 4px solid #c2a14e; padding-left: 10px; margin-bottom: 10px; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 8px 10px; font-size: 13px; border-bottom: 1px solid #efe7d6; }
  td.k { color: #7a6440; width: 45%; }
  td.v { color: #1a1208; font-weight: 600; }
  .foot { margin-top: 36px; border-top: 1px solid #e6dcc4; padding-top: 12px; font-size: 10px; color: #9b7a36; text-align: center; }
  @media print { body { padding: 24px; } }
</style></head>
<body>
  <div class="head">
    <div>
      <div class="brand">${escapeHtml(subtitle)}</div>
      <h1>${escapeHtml(title)}</h1>
      <div class="subtitle">Eco Connect · Farm Intelligence Report</div>
    </div>
    <div>
      <div class="seal">🦅</div>
      <div class="date">${escapeHtml(date)}</div>
    </div>
  </div>
  ${kpiHtml}
  ${sectionsHtml}
  <div class="foot">${escapeHtml(footer)}</div>
</body></html>`;

  // Primary path: render into a hidden same-origin iframe and print it.
  // This avoids pop-up blockers (which silently break window.open) and works
  // reliably across browsers. Falls back to a new window if the iframe fails.
  try {
    const iframe = document.createElement('iframe');
    iframe.setAttribute('aria-hidden', 'true');
    iframe.style.position = 'fixed';
    iframe.style.right = '0';
    iframe.style.bottom = '0';
    iframe.style.width = '0';
    iframe.style.height = '0';
    iframe.style.border = '0';
    document.body.appendChild(iframe);

    const doc = iframe.contentWindow.document;
    doc.open();
    doc.write(html);
    doc.close();

    const triggerPrint = () => {
      try {
        iframe.contentWindow.focus();
        iframe.contentWindow.print();
      } catch (err) {
        console.error('Iframe print failed, falling back to window:', err);
        printInNewWindow(html);
      }
      // Clean up after the print dialog has had time to open.
      setTimeout(() => {
        if (iframe.parentNode) iframe.parentNode.removeChild(iframe);
      }, 1000);
    };

    // Give the browser a tick to lay out the document before printing.
    if (iframe.contentWindow.document.readyState === 'complete') {
      setTimeout(triggerPrint, 200);
    } else {
      iframe.onload = () => setTimeout(triggerPrint, 200);
    }
  } catch (err) {
    console.error('Iframe export failed, falling back to window:', err);
    printInNewWindow(html);
  }
}

// Fallback: open a new window and print (used only if the iframe path fails).
function printInNewWindow(html) {
  const win = window.open('', '_blank', 'width=900,height=1000');
  if (!win) {
    alert('Please allow pop-ups to download the PDF report, or use your browser\u2019s Print option.');
    return;
  }
  win.document.open();
  win.document.write(html + '<script>window.onload=function(){window.focus();window.print();};<\/script>');
  win.document.close();
}

